#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false

    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    
    # Option for autocomplete
    autocomplete_method = "coc"

    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "lang#c"
clang_executable = "clang"
    [layer.clang_std]
    c = "c11"
    cpp = "c++1z"

[[layers]]
name = "lsp"
filetypes = ["c", "cpp"]
    [layers.override_cmd]
    c = ["clangd", "--limit-results=5"]
    cpp = ["clangd", "--limit-results=5"]

[[layers]]
name = "format"
enable = false

[[custom_plugins]]
repo = "rhysd/vim-clang-format"
merged = false
